### ISSUE TITLE
Errors while serving a request can crash Node.js

### ISSUE THREAD

**Issue by leccelecce** [dot4qu/Lineup-List#52]
This is a follow on from #32 

Sometimes, usually due to a null value, I get a crash in the app. I'm used to building webapps in Java frameworks, and normally a crash while serving a client request would throw an exception, but not terminate the entire app.

I assume there is a way to handle this more gracefully in Node.js 

```
D:\GitProjects\Lineup-List>node dist\server.js
LINEUPLIST_FORCE_HTTP set, skipping certs and starting an http ONLY local server
Resetting customize page to last known state and recieved unknown tracktype: null or undefined
D:\GitProjects\Lineup-List\dist\redis-helper.js:205
            for (const artistId of artistIds) {
                                   ^

TypeError: artistIds is not iterable
    at Object.<anonymous> (D:\GitProjects\Lineup-List\dist\redis-helper.js:205:36)
    at Generator.next (<anonymous>)
    at fulfilled (D:\GitProjects\Lineup-List\dist\redis-helper.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.7.0
```

**Comment by dot4qu** [comment]
Yeah there shouldn't be any crashes, there needs to be guards around wherever `artists` is coming from. Without looking, I'm guessing something is returning null for some reason and the code is expecting just an empty list for no artists. If this is within the code for saving the state of a users sections for a festival, there's a distinction between null and empty list. The former would mean nothing saved, so check all artist checkboxes, the latter would mean no artists should be checked.

**Comment by dot4qu** [comment]
Also I never get this crash though so I wonder what the difference is. Do you have steps to repro it?

**Comment by leccelecce** [comment]
Ah, I wasn't clear. I'm more talking about generic error handling in NodeJS / Express rather than the specific `artists` example above. Software will always contain bugs / missing checks or encounter recoverable runtime errors. Essentially, if a runtime error is encountered while handling a client HTTP request, and there are no specific error handlers configured, I'd just expect the framework to automatically return an HTTP 500 Internal Server Error to the client, rather than crash the whole process.

Looking briefly at https://expressjs.com/en/guide/error-handling.html it does suggest that Express _does_ have a built-in default error handler that will throw an HTTP 500 - so maybe this is being overridden somehow. I can try and debug and see what's happening with it.

**Comment by dot4qu** [comment]
Ah yes okay I see what you're saying. Yeah there is 100% a better way to set it up. The bare minimum would be to actually run the server correctly (aka like a systemd process that auto-restarts on crash) not the shitty way I'm doing it (manually starting it by executing the base js file). That'd be a bad UX, but better than the server potentially getting fully hung until it's manually restarted.

Like you're saying, I also think there is a better way to use express middleware to wrap every route handler with a global try/catch which would then default back to 500. I haven't actually looked into it though so if you find out a better way to do it I'm all ears
